services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - cluster.name=mycluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-es01:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 | grep -q "cluster_name"
      interval: 10s
      timeout: 10s
      retries: 120

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - node.name=es02
      - cluster.name=mycluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-es02:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 | grep -q "cluster_name"
      interval: 10s
      timeout: 10s
      retries: 120

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - "9202:9200"
      - "9303:9300"
    environment:
      - node.name=es03
      - cluster.name=mycluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-es03:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 | grep -q "cluster_name"
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]
      - XPACK_SECURITY_ENABLED=false

volumes:
  es-data-es01:
  es-data-es02:
  es-data-es03:
